export const SHOW_ERROR = "SHOW_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";


export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const DEVICE_DATA_FETCH_START = "DEVICE_DATA_FETCH_START";
export const DEVICE_DATA_FETCH_SUCCESS = "DEVICE_DATA_FETCH_SUCCESS";
export const DEVICE_DATA_FETCH_FAIL = "DEVICE_DATA_FETCH_FAIL";

export const SET_ACTIVE_DEVICE = "SET_ACTIVE_DEVICE";
export const SET_ACTIVE_DEVICE_DATA = "SET_ACTIVE_DEVICE_DATA";